### ISSUE TITLE
Players can add their own name to the available nicks

### ISSUE THREAD

**Issue by SalmonGER** [UltimateDevs/RandomNick#1]
Hello!

First of all I really like the idea of this plugin and it definetly works.
But players who aren't nicked can use /nick off while they aren't nicked.
/nick off then adds their username without checking to the available nicknames and the next nick user could get the name of that player.

**Comment by erkam2002** [comment]
Aber es macht nix aus also ist es normaler weisse egal oder ? 
Willst du auch der Gruppe beitreten?

**Comment by SalmonGER** [comment]
@erkam2002 Dieser Fehler macht es möglich, dass zwei Personen im Chat den gleichen Namen benutzen können.
Der Gruppe beizutreten muss ich leider ablehnen. Tut mir leid. :(

**Comment by erkam2002** [comment]
ok schade

**Comment by SalmonGER** [comment]
@erkam2002 Falls ich die Erlaubnis kriege, könnte ich am Plugin arbeiten um zu verhindern, dass dies passiert.

**Comment by erkam2002** [comment]
Ok kannst du denn keine pull request erstellen?

**Comment by SalmonGER** [comment]
Mach ich. :)

**Comment by erkam2002** [comment]
:D
